### ISSUE TITLE
Compatibility with Ubuntu Core with Raspberry Pi/Cloudflared/PiHole

### ISSUE THREAD

**Issue by ProfessorManhattan** [konstruktoid/ansible-role-hardening#18]
Hey, this seems like a really cool script so thanks! I am wondering if I would be able to use this with a Raspberry Pi with PiHole and cloudflared installed as well. I realize this is a general question. Are there any modules included in this that might impact a PiHole setup? I notice there are DNS configurations but the PiHole needs to manage those itself.

**Comment by konstruktoid** [comment]
Hi @ProfessorManhattan and thanks!
I'm using the playbook on a Ubuntu Raspberry Pi without any issues.

The DNS changes in https://github.com/konstruktoid/ansible-role-hardening/blob/master/templates/etc/systemd/resolved.conf.j2 shouldn't effect any PiHole settings since it's standard `systemd` settings.
Just check so the DNS servers are correct (https://github.com/konstruktoid/ansible-role-hardening/blob/master/defaults/main.yml#L3-L5)
