### ISSUE TITLE
[QUESTION] Question about PAM hardening

### ISSUE THREAD

**Issue by polachz** [konstruktoid/ansible-role-hardening#35]
**Question about PAM hardening**

Hallo.

I have a problem on CentOS 8.3 with new user login.

I have created new user after role is applied, but user is not able to login on the console

Due this I have started analyze the PAM modifications provided by the role

At first, i have found that role copied 

- common-auth
- common-password
- common-account

files on all platforms, but seems that on RedHat family these files are not used (included) by other pam config files. Then are really necessary to be copied here? 

Why on RHEL family the sugroup is defined? Is here idea to use it as a wheel replacement or something else? 

Thank you for your answers.

ZP

**Comment by konstruktoid** [comment]
Hi again @polachz, yeah those `common-*` should only be, and only is if I recall correctly, used on Debian family distributions.
Will update with a `when:`

The `sugroup` is defined to enforce the use of `sudo`, since we got better control with `sudo` and better logging. See e.g. CIS Ubuntu benchmark "5.6 Ensure access to the su command is restricted"

**Comment by konstruktoid** [comment]
`/etc/pam.d/common-password` in `/etc/pam.d/password-auth` on CentOS, but that file is managed by `authselect`

**Comment by polachz** [comment]
Ok, thank you for the explanation.  On the PAM fiels, i'm not as strong as I can be..

Thank you for your good work on the role !
